### PR TITLE
added german as languange

### PR DESCRIPTION
**Pull request by mschneider82**
Not perfect yet, but everything translated

### CODE REVIEW

**Comment by hugolgst** [comment]
That's really great!
I am going to add the countries translations in German.
Could you also translate the website?

**Comment by mschneider82** [comment]
@hugolgst  it seems it doesnt work: ill get a panic "Cannot make dot product between these two matrix."

just try to ask: "Wie geht's" or "Wie ist die Hauptstadt von der Schweiz?"

**Comment by hugolgst** [comment]
I am going to investigate that

**Comment by hugolgst** [comment]
The ArticleCountries function for German was not implemented and since I didn't add a check to see if it exists it crashed. I fixed that, thanks for the report.

**Pull request merged**
